name: lj_web3_tron_sdk
description: SDK can create ETH 、BSC chain and coins.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
homepage: https://github.com/JamesBondMine/lj_web3_tron_sdk

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:

  web3dart: ^2.6.1

  bip39: ^1.0.6

  bip32: ^2.0.0
  # 图片缓存
  cached_network_image: ^3.2.2
  # 网络请求库
  dio: ^5.3.0

  webview_flutter: ^4.0.0
  flutter:
    sdk: flutter

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

flutter:
  uses-material-design: true
  assets:
    - packages/lj_web3_tron_sdk/assets/images/ETH.png
    - packages/lj_web3_tron_sdk/assets/images/BSC.png
    - packages/lj_web3_tron_sdk/assets/images/BNB.png
    - packages/lj_web3_tron_sdk/assets/images/TRX.png
    - packages/lj_web3_tron_sdk/assets/images/USDT.png
    - packages/lj_web3_tron_sdk/assets/images/USDC.png
    - packages/lj_web3_tron_sdk/assets/images/CREAM.png
    - packages/lj_web3_tron_sdk/assets/images/WETH.png
    - packages/lj_web3_tron_sdk/assets/images/YFI.png
    - packages/lj_web3_tron_sdk/assets/images/BUSD.png
    - packages/lj_web3_tron_sdk/assets/images/WTRX.png
    - packages/lj_web3_tron_sdk/assets/json/config.json
    
