name: lj_web3_tron_sdk
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
homepage: https://github.com/JamesBondMine/lj_web3_tron_sdk

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:

  web3dart: ^2.6.1

  bip39: ^1.0.6

  bip32: ^2.0.0
  # 图片缓存
  cached_network_image: ^3.2.2
  # 网络请求库
  dio: ^5.3.0

  webview_flutter: ^4.0.0

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
